import uuid
from src.agent.base import get_base_agent
from src.utils import autolog, get_logger
from agno.models.message import Message

logger = get_logger(__name__)


@autolog()
async def run_subagent(message: str) -> str:
    """Runs a sub-agent with the provided message as input. The sub-agent will have access to the same tools as the main agent, but will operate with a fresh context. This is useful for delegating complex subtasks that require multiple steps or tool calls, allowing the main agent to offload work while maintaining modularity and context efficiency.

    IMPORTANT: The sub-agent's output is NOT sent directly to the user. It is returned as a regular tool call output, just like any other tool. The calling agent is responsible for reviewing the returned data and then either presenting relevant information to the user or using it for further analysis and decision-making.

    Args:
        message (str): The input message to provide to the sub-agent. This should include all necessary information and instructions for the sub-agent to complete its task.

    Returns:
        str: The final response generated by the sub-agent after processing the input message and utilizing any necessary tools. This response is returned to the calling agent, not to the user.
    """
    from src.agent.tools import get_tools

    new_conversation_id = uuid.uuid4().hex
    subagent = get_base_agent(
        tools=get_tools(conversation_id=new_conversation_id),
    )
    logger.info(f"Running sub-agent for conversation_id: {new_conversation_id}...")
    subagent_output = await subagent.arun(
        [
            Message(
                role="user",
                content=message,
            )
        ]
    )

    logger.info(f"Sub-agent completed for conversation_id: {new_conversation_id}")
    content: str = subagent_output.content  # type: ignore

    return content
